apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
        - name: app-main
          image: rahulpoonia20793/nginxapp:latest
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: log-volume
              mountPath: /var/log
        - name: nginx-sidecar
          image: nginx:latest
          volumeMounts:
            - name: nginx-conf-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
          ports:
            - containerPort: 80
      volumes:
        - name: nginx-conf-volume
          configMap:
            name: nginx-configmap
        - name: log-volume
          emptyDir: {}

